set_wallpaper: show a notification (via kdialog) if wallpaper changing on Plasma 5 fails
dbus scripts not working when the widgets are locked is unfortunately a common issue; see https://github.com/varietywalls/variety/issues/17

diff --git a/data/scripts/set_wallpaper b/data/scripts/set_wallpaper
--- a/data/scripts/set_wallpaper
+++ b/data/scripts/set_wallpaper
@@ -131,7 +131,17 @@ if [ "${KDE_FULL_SESSION}" == "true" ]; then
         }
         "
         # Reuse the exit code from qdbus
-        exit "$?"
+        qdbus_exitcode="$?"
+
+        if [[ "$qdbus_exitcode" -ne 0 ]]; then
+            # If the script fails, show a notification.
+            kdialog --title "Variety: cannot change Plasma wallpaper" --passivepopup "Could not change the Plasma 5 wallpaper; \
+                make sure that you're using Plasma 5.7+ and have widgets unlocked.\n----\n \
+                Due to Plasma limitations, external programs cannot automatically change the wallpaper when the widgets are locked.\n \
+                See https://git.io/vprpM for more information." --icon variety 10  # Final number is the length of the popup
+        fi
+        exit "$qdbus_exitcode"
+
     else
         WALLDIR="$(xdg-user-dir PICTURES)/variety-wallpaper"
         mkdir -p "$WALLDIR"
